export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILD = 'FETCH_INGREDIENTS_FAILD';

export const PUCHASE_BURGER_SUCCESS = 'PUCHASE_BURGER_SUCCESS';
export const PUCHASE_BURGER_FAIL = 'PUCHASE_BURGER_FAIL';